# Generated by Django 4.1.6 on 2023-02-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('gamer_tag', models.CharField(max_length=50)),
                ('elo', models.PositiveIntegerField(default=1000)),
                ('highest_elo', models.PositiveIntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-gamer_tag',),
            },
        ),
    ]
