# Generated by Django 4.1.6 on 2023-02-10 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ggstelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('gamer_tag',)},
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('players', models.ManyToManyField(to='ggstelo.player')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('display_score', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('players', models.ManyToManyField(to='ggstelo.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggstelo.tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_match_set', to='ggstelo.player')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
