# Generated by Django 4.1.6 on 2023-02-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ggstelo', '0004_match_loser_alter_match_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('id',), 'verbose_name_plural': 'matches'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='display_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_match_set', to='ggstelo.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_elo_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_score',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_match_set', to='ggstelo.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_elo_change',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_score',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ggstelo.tournament'),
        ),
    ]
