# Generated by Django 4.1.6 on 2023-02-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggstelo', '0005_alter_match_options_remove_match_display_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1_elo_change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_elo_change',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
