# Generated by Django 4.1.6 on 2023-02-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggstelo', '0006_alter_match_player1_elo_change_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
    ]
