# Generated by Django 4.1.6 on 2023-02-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggstelo', '0007_remove_tournament_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
