# Generated by Django 4.1.6 on 2023-03-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggstelo', '0009_alter_match_player1_elo_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(),
        ),
    ]
