# Generated by Django 4.1.6 on 2023-03-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggstelo', '0010_alter_player_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('elo',)},
        ),
    ]
