# Generated by Django 4.1.6 on 2023-03-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggstelo', '0013_alter_player_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('-elo',)},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ('created_at',)},
        ),
    ]
